### ISSUE TITLE
Simulation API

### ISSUE THREAD

**Issue by Explicious** [lenstronomy/lenstronomy-tutorials#2]
There is a minor error in the simulation_api notebook 13/14/15 where SimAPI() calls kwargs_numerics as a parameter although SimAPI does not take this parameter, rather SimAPI.image_model_class() seems to take this. Also, running that cell of code after moving kwargs_numerics to the image_model_class() gives a TypeError in SimulationAPI.data_api in ._init_() that gives the error that .__init__() got an unexpected keyword argument psf_model.

**Comment by sibirrer** [comment]
The current notebooks were/should be compatible with the pip version 0.9.2. The current master branch was a bit ahead. I pushed the notebooks compatible with the current master branch and will release a new lenstronomy version based on the current master branch very soon (0.9.3). Please close the issue if this solves it or let me know otherwise. Thanks for your feedback!

**Comment by Explicious** [comment]
Thanks for the clarification!
